keys:
  - &admin_julius EBE7 5BC0 5820 6BC9 F440  895F F7D6 E464 4ACD 05A4
  - &admin_bikerpenguin67 age1qdjtq9nazunecnjykdqn5uwnch4qj9j2j94sxf7c36xpkwytkssqg3py5k
  - &server_clematis age1pqkkuwmn4wdyk6ncptpxttjnqpuu4gk9sgwwqds2wetvjmv8s48qwfwf5x
creation_rules:
  - path_regex: ^sops/secrets.yaml$
    key_groups:
      - pgp:
          - *admin_julius
        age:
          - *admin_bikerpenguin67
          - *server_clematis
